# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'socialsocial' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for socialsocial

  target 'socialsocial-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'socialsocialTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'socialsocial-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for socialsocial-tvOS

  target 'socialsocial-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
